import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip as RTooltip, XAxis, YAxis } from "recharts";
import { CreditCard, Search, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EmptyState, GlossyIcon, PageHeader, Panel, StatusPill, TableShell, Td, Th, Tr, money } from "@/components/admin/kit";
import { api, type ApiPayment } from "@/lib/api";

export const Route = createFileRoute("/admin/payments")({ head: () => ({ meta: [{ title: "Payments — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: PaymentsPage });
const tone = { paid: "emerald", pending: "amber", refunded: "blue", failed: "red" } as const;
const date = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value));

function PaymentsPage() {
  const [q, setQ] = useState(""); const payments = useQuery({ queryKey: ["admin-payments"], queryFn: () => api.payments.list("?limit=100") }); const dashboard = useQuery({ queryKey: ["admin-payment-chart"], queryFn: api.admin.dashboard });
  const rows = useMemo(() => (payments.data ?? []).filter((payment) => [payment._id, payment.customer?.name, payment.customer?.email, payment.booking?.reference].join(" ").toLowerCase().includes(q.toLowerCase())), [payments.data, q]);
  const gross = (payments.data ?? []).reduce((sum, payment) => sum + payment.amount, 0); const commission = (payments.data ?? []).reduce((sum, payment) => sum + payment.commission, 0); const tax = (payments.data ?? []).reduce((sum, payment) => sum + payment.tax, 0); const refunded = (payments.data ?? []).filter((payment) => payment.status === "refunded").reduce((sum, payment) => sum + payment.amount, 0); const series = (dashboard.data?.weeklySeries ?? []).map((item: { label: string; revenue: number }) => ({ label: item.label, revenue: item.revenue }));
  return <><PageHeader title="Payments" description="Live transactions, commissions, tax, and refund activity." crumbs={[{ label: "Payments" }]} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Gross volume", money(gross), "blue"], ["Commission earned", money(commission), "emerald"], ["Tax collected", money(tax), "amber"], ["Refunded", money(refunded), "red"]].map(([label, value, color]) => <div key={label} className="flex items-center gap-4 rounded-2xl border border-border bg-card p-4"><GlossyIcon icon={CreditCard} tone={color as "blue"} /><div><p className="text-xl font-semibold tabular-nums tracking-tight">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></div>)}</div>
    <div className="mt-4 grid gap-4"><Panel title="Revenue trend"><ResponsiveContainer width="100%" height={220}><AreaChart data={series} margin={{ left: -18, right: 6 }}><defs><linearGradient id="pay" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="oklch(0.68 0.17 155)" stopOpacity={0.35} /><stop offset="100%" stopColor="oklch(0.68 0.17 155)" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="oklch(0.92 0.01 255)" vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={11} stroke="oklch(0.52 0.02 255)" /><YAxis tickLine={false} axisLine={false} fontSize={11} stroke="oklch(0.52 0.02 255)" /><RTooltip contentStyle={{ borderRadius: 12, border: "1px solid oklch(0.92 0.01 255)", fontSize: 12 }} /><Area type="monotone" dataKey="revenue" stroke="oklch(0.68 0.17 155)" strokeWidth={2.5} fill="url(#pay)" /></AreaChart></ResponsiveContainer></Panel>
      <Panel bodyClassName="p-0"><Tabs defaultValue="transactions"><div className="flex flex-wrap items-center gap-3 border-b border-border p-4"><TabsList><TabsTrigger value="transactions">Transactions</TabsTrigger><TabsTrigger value="invoices">Invoices</TabsTrigger><TabsTrigger value="refunds">Refunds</TabsTrigger></TabsList><div className="relative ml-auto min-w-[200px] max-w-xs flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search payments" className="h-9 pl-9" /></div></div><TabsContent value="transactions" className="m-0"><PaymentTable loading={payments.isLoading} error={payments.isError} rows={rows} /></TabsContent><TabsContent value="invoices" className="m-0"><PaymentTable loading={payments.isLoading} error={payments.isError} rows={rows.filter((payment) => payment.status === "paid")} invoice /></TabsContent><TabsContent value="refunds" className="m-0"><PaymentTable loading={payments.isLoading} error={payments.isError} rows={rows.filter((payment) => payment.status === "refunded")} refund /></TabsContent></Tabs></Panel></div></>;
}
function PaymentTable({ rows, loading, error, invoice = false, refund = false }: { rows: ApiPayment[]; loading: boolean; error: boolean; invoice?: boolean; refund?: boolean }) { if (loading) return <div className="flex justify-center py-16 text-muted-foreground"><LoaderCircle className="mr-2 h-5 w-5 animate-spin" />Loading payments…</div>; if (error) return <EmptyState icon={CreditCard} title="Could not load payments" description="Check the backend connection and administrator session." />; if (!rows.length) return <EmptyState icon={CreditCard} title={refund ? "No refunds found" : "No payments found"} description="Transactions appear here when payment records are created." />; return <TableShell><thead><tr><Th>{invoice ? "Invoice" : "Payment"}</Th><Th>Booking</Th><Th>Customer</Th>{!invoice && <Th>Method</Th>}<Th className="text-right">Amount</Th>{!invoice && <><Th className="text-right">Commission</Th><Th className="text-right">Tax</Th></>}<Th>Status</Th><Th>Date</Th></tr></thead><tbody>{rows.map((payment) => <Tr key={payment._id}><Td className="font-medium">{invoice ? `INV-${payment._id.slice(-8).toUpperCase()}` : payment._id}</Td><Td className="text-primary">{payment.booking?.reference || "—"}</Td><Td>{payment.customer?.name || "—"}</Td>{!invoice && <Td className="text-muted-foreground">{payment.method}</Td>}<Td className="text-right font-semibold">{money(invoice ? payment.amount + payment.tax : payment.amount)}</Td>{!invoice && <><Td className="text-right">{money(payment.commission)}</Td><Td className="text-right">{money(payment.tax)}</Td></>}<Td><StatusPill label={payment.status} tone={tone[payment.status]} /></Td><Td className="text-muted-foreground">{date(payment.date)}</Td></Tr>)}</tbody></TableShell>; }
