import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Search, Users, PauseCircle, PlayCircle, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { EmptyState, PageHeader, Panel, StatusPill, TableShell, Td, Th, Tr, money, num } from "@/components/admin/kit";
import { api, type ApiUser } from "@/lib/api";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/customers")({ head: () => ({ meta: [{ title: "Customers — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: CustomersPage });
const date = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—";
const name = (user: ApiUser) => user.name || "Unnamed customer";

function CustomersPage() {
  const [q, setQ] = useState(""); const [active, setActive] = useState<ApiUser | null>(null); const client = useQueryClient();
  const users = useQuery({ queryKey: ["admin-customers"], queryFn: () => api.users.list("?role=customer&limit=100") });
  const bookings = useQuery({ queryKey: ["admin-customer-bookings"], queryFn: () => api.admin.bookings("?limit=100") });
  const setActiveStatus = useMutation({ mutationFn: ({ id, isActive }: { id: string; isActive: boolean }) => api.users.setActive(id, isActive), onSuccess: (updated) => { client.invalidateQueries({ queryKey: ["admin-customers"] }); setActive(updated); toast.success(`Customer ${updated.isActive ? "reactivated" : "suspended"}`); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Could not update customer") });
  const rows = (users.data ?? []).filter((user) => [user.name, user.email, user.city].join(" ").toLowerCase().includes(q.toLowerCase()));
  const customerBookings = active ? (bookings.data ?? []).filter((booking: any) => (booking.customer?._id ?? booking.customer?.id) === active._id) : [];
  const spend = customerBookings.reduce((sum: number, booking: any) => sum + (booking.price?.total ?? 0), 0);
  return <><PageHeader title="Customers" description="Live customer accounts and their booking activity." crumbs={[{ label: "Customers" }]} />
    <Panel bodyClassName="p-0"><div className="border-b border-border p-4"><div className="relative max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search customers" className="h-9 pl-9" /></div></div>{users.isLoading ? <Loading /> : users.isError ? <EmptyState icon={Users} title="Could not load customers" description="Check the backend connection and administrator session." /> : rows.length === 0 ? <EmptyState icon={Users} title="No customers yet" description="Customers appear here after registering on the website." /> : <TableShell><thead><tr><Th>Customer</Th><Th>Contact</Th><Th>City</Th><Th>Joined</Th><Th>Status</Th><Th /></tr></thead><tbody>{rows.map((user) => <Tr key={user._id} onClick={() => setActive(user)}><Td><span className="flex items-center gap-2"><Avatar className="h-8 w-8"><AvatarImage src={user.avatarUrl} alt={name(user)} /><AvatarFallback>{name(user)[0]}</AvatarFallback></Avatar><span className="font-medium">{name(user)}</span></span></Td><Td className="text-muted-foreground">{user.email}</Td><Td>{user.city || "—"}</Td><Td className="text-muted-foreground">{date(user.createdAt)}</Td><Td><StatusPill label={user.isActive ? "Active" : "Suspended"} tone={user.isActive ? "emerald" : "amber"} /></Td><Td className="text-right"><Button size="sm" variant="ghost">View</Button></Td></Tr>)}</tbody></TableShell>}</Panel>
    <Sheet open={!!active} onOpenChange={(open) => !open && setActive(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-lg">{active && <><SheetHeader><SheetTitle>Customer profile</SheetTitle></SheetHeader><div className="space-y-5 p-5"><div className="flex items-center gap-3"><Avatar className="h-14 w-14"><AvatarImage src={active.avatarUrl} alt={name(active)} /><AvatarFallback>{name(active)[0]}</AvatarFallback></Avatar><div><p className="text-base font-semibold">{name(active)}</p><p className="text-xs text-muted-foreground">{active.email} · {active.phone || "No phone"}</p></div></div><div className="grid grid-cols-3 gap-2 text-center">{[["Bookings", num(customerBookings.length)], ["Spend", money(spend)], ["Since", date(active.createdAt)]].map(([label, value]) => <div key={label} className="rounded-xl bg-muted/60 p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="text-sm font-semibold tabular-nums">{value}</p></div>)}</div><section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Recent bookings</h3>{bookings.isLoading ? <p className="text-sm text-muted-foreground">Loading booking history…</p> : <ul className="space-y-2">{customerBookings.slice(0, 5).map((booking: any) => <li key={booking._id} className="flex items-center justify-between rounded-xl border border-border p-2.5 text-sm"><span>{booking.service?.name || "Service"}</span><span className="text-xs tabular-nums text-muted-foreground">{date(booking.scheduledFor)} · {money(booking.price?.total ?? 0)}</span></li>)}{!customerBookings.length && <li className="text-sm text-muted-foreground">No bookings yet.</li>}</ul>}</section><Button variant="outline" className="w-full gap-1.5" disabled={setActiveStatus.isPending} onClick={() => setActiveStatus.mutate({ id: active._id, isActive: !active.isActive })}>{setActiveStatus.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : active.isActive ? <PauseCircle className="h-4 w-4" /> : <PlayCircle className="h-4 w-4" />}{active.isActive ? "Suspend customer" : "Reactivate customer"}</Button></div></>}</SheetContent></Sheet>
  </>;
}
function Loading() { return <div className="flex justify-center py-16 text-muted-foreground"><LoaderCircle className="mr-2 h-5 w-5 animate-spin" />Loading customers…</div>; }
