import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Star, MapPin, Award, Briefcase, Clock, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { technicians } from "@/data/servicepro";
import { api, apiConfigured, type ApiTechnician } from "@/lib/api";

export const Route = createFileRoute("/technicians/$slug")({
  head: () => ({ meta: [{ title: "Technician profile — ServicePro" }, { name: "robots", content: "noindex" }] }),
  component: TechnicianProfile,
});

function TechnicianProfile() {
  const { slug } = Route.useParams();
  const { data: live, isLoading, isError } = useQuery({ queryKey: ["technician", slug], enabled: apiConfigured, queryFn: () => api.technicians.detail(slug) });
  const tech = live ? toDisplayTechnician(live) : !apiConfigured ? technicians.find((item) => item.slug === slug) : undefined;
  if (apiConfigured && isLoading) return <div className="mx-auto grid min-h-[60vh] place-items-center text-sm text-muted-foreground"><LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> Loading technician…</div>;
  if (!tech || isError) return <div className="mx-auto max-w-4xl px-4 py-20"><h1 className="text-3xl font-semibold">Technician not found</h1><Button asChild variant="outline" className="mt-6"><Link to="/technicians">Browse technicians</Link></Button></div>;
  return <div className="mx-auto max-w-6xl px-4 py-12"><Button asChild variant="ghost" size="sm" className="mb-6"><Link to="/technicians"><ArrowLeft className="mr-1 h-4 w-4" /> All technicians</Link></Button><div className="card-elevated overflow-hidden"><div className="h-40 bg-gradient-to-br from-primary to-[oklch(0.4_0.22_270)]" /><div className="px-8 pb-8"><div className="-mt-16 flex flex-col items-start gap-6 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-5"><Avatar className="h-32 w-32 ring-4 ring-white shadow-[var(--shadow-floating)]"><AvatarImage src={tech.avatar} alt={tech.name} /><AvatarFallback>{tech.name[0]}</AvatarFallback></Avatar><div className="pb-2"><h1 className="text-3xl font-semibold tracking-tight">{tech.name}</h1><div className="mt-2 flex items-center gap-3 text-sm text-muted-foreground"><span className="inline-flex items-center gap-1"><MapPin className="h-4 w-4" /> {tech.city}</span><span className="inline-flex items-center gap-1"><Star className="h-4 w-4 fill-warning text-warning" /> {tech.rating}</span></div></div></div>{tech.available ? <Button asChild size="lg" className="btn-press shadow-[var(--shadow-glow)]"><Link to="/book" search={{ technician: tech.id }}>Book this technician</Link></Button> : <Button size="lg" disabled>Currently unavailable</Button>}</div></div></div><div className="mt-10 grid gap-8 lg:grid-cols-3"><div className="space-y-8 lg:col-span-2"><Section title="About"><p className="text-muted-foreground">{tech.bio || "Verified ServicePro professional."}</p></Section><Section title="Specializations"><div className="flex flex-wrap gap-2">{tech.specializations.map((skill) => <Badge key={skill} variant="secondary" className="rounded-full">{skill}</Badge>)}</div></Section><Section title="Verification"><p className="text-sm text-muted-foreground">This technician has been approved by ServicePro and is eligible for bookings in their listed service areas.</p></Section></div><aside className="space-y-4"><div className="card-elevated space-y-4 p-6"><Stat icon={Briefcase} label="Experience" value={`${tech.experienceYears} years`} /><Stat icon={Award} label="Completed jobs" value={tech.completedJobs.toLocaleString()} /><Stat icon={Clock} label="Availability" value={tech.available ? "Available today" : "Currently unavailable"} /></div><div className="card-elevated p-6"><p className="eyebrow">Hourly rate</p><p className="mt-1 text-3xl font-bold">${tech.hourlyRate}<span className="text-base font-normal text-muted-foreground">/hr</span></p></div></aside></div></div>;
}

function toDisplayTechnician(technician: ApiTechnician) { return { id: technician._id, name: technician.user?.name ?? "ServicePro technician", avatar: technician.user?.avatarUrl ?? "", city: technician.city, rating: technician.rating, experienceYears: technician.experienceYears, completedJobs: technician.jobsCompleted, specializations: technician.services, available: technician.isAvailable, hourlyRate: technician.hourlyRate, bio: "" }; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <div className="card-elevated p-6"><h3 className="text-sm font-semibold uppercase tracking-widest text-muted-foreground">{title}</h3><div className="mt-3">{children}</div></div>; }
function Stat({ icon: I, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string }) { return <div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-primary-soft text-primary"><I className="h-4 w-4" /></div><div><p className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</p><p className="text-sm font-semibold">{value}</p></div></div>; }
