import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ArrowLeft, Check, X, MessageSquareWarning, ExternalLink, FileText, MapPin, Clock, Phone, Mail, LoaderCircle, PartyPopper } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { GlossyIcon, PageHeader, Panel, StatusPill } from "@/components/admin/kit";
import { api, API_BASE_URL, type ApiTechnician } from "@/lib/api";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/verification/$techId")({ head: () => ({ meta: [{ title: "Application review — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: ApplicationReview });
const meta = { pending: { label: "Pending", tone: "amber" as const }, under_review: { label: "Under review", tone: "blue" as const }, rejected: { label: "Rejected", tone: "red" as const }, suspended: { label: "Suspended", tone: "slate" as const }, approved: { label: "Approved", tone: "emerald" as const } };
const name = (tech: ApiTechnician) => tech.user?.name || "Unnamed technician";
const date = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const fileUrl = (url: string) => url.startsWith("http") ? url : `${API_BASE_URL.replace(/\/api\/v1$/, "")}${url}`;
const labelForDocument = (kind: string) => ({ id_card: "Government ID", certificate: "Degree or trade certificate", insurance: "Insurance", background_check: "Background check" }[kind] ?? kind);

function ApplicationReview() {
  const { techId } = Route.useParams(); const client = useQueryClient(); const [reason, setReason] = useState(""); const [approved, setApproved] = useState(false);
  const { data: tech, isLoading, isError } = useQuery({ queryKey: ["admin-technician", techId], queryFn: () => api.technicians.adminDetail(techId) });
  const decision = useMutation({ mutationFn: ({ status, notes }: { status: "under_review" | "approved" | "rejected" | "suspended"; notes?: string }) => api.technicians.updateVerification(techId, status, notes), onSuccess: (updated) => { client.setQueryData(["admin-technician", techId], updated); client.invalidateQueries({ queryKey: ["admin-technicians"] }); client.invalidateQueries({ queryKey: ["admin-verification"] }); if (updated.verificationStatus === "approved") setApproved(true); toast.success(`Application marked ${updated.verificationStatus?.replace("_", " ")}`); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Could not update the application") });
  if (isLoading) return <div className="flex justify-center py-20 text-muted-foreground"><LoaderCircle className="mr-2 h-5 w-5 animate-spin" />Loading application…</div>;
  if (isError || !tech) return <div className="py-20 text-center"><p className="text-sm text-muted-foreground">Application {techId} could not be found.</p><Button asChild size="sm" className="mt-4"><Link to="/admin/verification">Back to queue</Link></Button></div>;
  if (approved) return <div className="grid place-items-center py-24 text-center animate-scale-in"><GlossyIcon icon={PartyPopper} tone="emerald" size="lg" /><h1 className="mt-4 text-2xl font-semibold tracking-tight">{name(tech)} is approved</h1><p className="mt-2 max-w-md text-sm text-muted-foreground">The technician can now appear in customer listings and receive bookings.</p><div className="mt-6 flex gap-2"><Button asChild variant="outline" size="sm"><Link to="/admin/verification">Back to queue</Link></Button><Button asChild size="sm"><Link to="/admin/technicians">Open technician list</Link></Button></div></div>;
  const status = tech.verificationStatus ?? "pending";
  return <><PageHeader title={name(tech)} description={`${tech.experienceYears} years experience · applied ${date(tech.createdAt)}`} crumbs={[{ label: "Verification Queue", to: "/admin/verification" }, { label: tech._id }]} actions={<><Button asChild variant="ghost" size="sm" className="gap-1.5"><Link to="/admin/verification"><ArrowLeft className="h-4 w-4" /> Queue</Link></Button><Button variant="outline" size="sm" className="gap-1.5" disabled={decision.isPending} onClick={() => decision.mutate({ status: "under_review", notes: "Additional information requested by administrator." })}><MessageSquareWarning className="h-4 w-4" /> Request info</Button><Dialog><DialogTrigger asChild><Button variant="outline" size="sm" className="gap-1.5 text-destructive" disabled={decision.isPending}><X className="h-4 w-4" /> Reject</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Reject {name(tech)}?</DialogTitle><DialogDescription>A reason is required and will be saved with this application.</DialogDescription></DialogHeader><Textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Explain what needs to change…" /><DialogFooter><Button variant="destructive" disabled={reason.trim().length < 8 || decision.isPending} onClick={() => decision.mutate({ status: "rejected", notes: reason.trim() })}>{decision.isPending && <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />}Reject application</Button></DialogFooter></DialogContent></Dialog><Dialog><DialogTrigger asChild><Button size="sm" className="btn-press gap-1.5" disabled={decision.isPending}><Check className="h-4 w-4" /> Approve</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Approve {name(tech)}?</DialogTitle><DialogDescription>They will immediately be visible to customers and can receive bookings.</DialogDescription></DialogHeader><DialogFooter><Button disabled={decision.isPending} onClick={() => decision.mutate({ status: "approved" })}>{decision.isPending && <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />}Approve technician</Button></DialogFooter></DialogContent></Dialog></>} />
    <div className="grid gap-4 xl:grid-cols-3"><div className="space-y-4 xl:col-span-2"><Panel><div className="flex flex-wrap items-center gap-4"><Avatar className="h-16 w-16 ring-2 ring-primary/20"><AvatarImage src={tech.user?.avatarUrl} alt={name(tech)} /><AvatarFallback>{name(tech)[0]}</AvatarFallback></Avatar><div className="mr-auto"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">{name(tech)}</h2><StatusPill {...meta[status]} /></div><p className="mt-1 text-sm text-muted-foreground">{tech.bio || "No biography submitted."}</p></div></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Info label="Email" value={tech.user?.email} icon={Mail} /><Info label="Phone" value={tech.user?.phone} icon={Phone} /><Info label="City" value={tech.city} icon={MapPin} /><Info label="Experience" value={`${tech.experienceYears} years`} icon={Clock} /><Info label="Hourly rate" value={tech.hourlyRate ? `$${tech.hourlyRate}` : "Not set"} icon={FileText} /><Info label="Availability" value={tech.isAvailable ? "Available" : "Unavailable"} icon={Clock} /></dl></Panel>
      <Panel title="Documents" description="Open each uploaded file to verify its legibility and details."><div className="grid gap-3 sm:grid-cols-2">{tech.documents?.length ? tech.documents.map((document) => <div key={`${document.kind}-${document.url}`} className="rounded-xl border border-border p-3"><div className="flex items-center justify-between"><FileText className="h-6 w-6 text-muted-foreground" /><Button asChild size="sm" variant="outline"><a href={fileUrl(document.url)} target="_blank" rel="noreferrer">Open <ExternalLink className="ml-1 h-3.5 w-3.5" /></a></Button></div><div className="mt-3"><p className="text-sm font-medium">{labelForDocument(document.kind)}</p><p className="text-[11px] text-muted-foreground">Uploaded {date(document.uploadedAt)}</p></div><div className="mt-3"><StatusPill label={document.verified ? "Verified" : "Needs check"} tone={document.verified ? "emerald" : "amber"} /></div></div>) : <p className="text-sm text-muted-foreground">No documents were uploaded.</p>}</div></Panel></div>
      <div className="space-y-4"><Panel title="Skills & services"><div className="flex flex-wrap gap-1.5">{tech.services.length ? tech.services.map((service) => <span key={service} className="rounded-lg bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">{service}</span>) : <span className="text-sm text-muted-foreground">No services selected</span>}</div></Panel><Panel title="Verification history"><ol className="relative space-y-4 border-l border-border pl-4 text-sm"><History dot="bg-primary" text="Application submitted" date={date(tech.createdAt)} /><History dot="bg-border" text="Documents received" date={date(tech.createdAt)} />{tech.reviewedAt && <History dot={status === "rejected" ? "bg-destructive" : "bg-primary"} text={`Status changed to ${meta[status].label}`} date={date(tech.reviewedAt)} />}{tech.reviewNotes && <li className="rounded-lg bg-muted p-2 text-xs text-muted-foreground">Review note: {tech.reviewNotes}</li>}</ol></Panel></div></div>
  </>;
}
function Info({ label, value, icon: Icon }: { label: string; value?: string; icon: React.ComponentType<{ className?: string }> }) { return <div><dt className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 flex items-center gap-1.5 text-sm"><Icon className="h-3.5 w-3.5 text-muted-foreground" />{value || "—"}</dd></div>; }
function History({ dot, text, date }: { dot: string; text: string; date: string }) { return <li className="relative"><span className={`absolute -left-[21px] top-1.5 h-2.5 w-2.5 rounded-full ${dot} ring-4 ring-card`} />{text}<span className="block text-[11px] text-muted-foreground">{date}</span></li>; }
