import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CalendarCheck, CheckCircle2, Clock3, DollarSign, LoaderCircle, ShieldCheck, Star, UserPlus, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { GlossyIcon, PageHeader, Panel, StatusPill, money, num } from "@/components/admin/kit";
import { api } from "@/lib/api";
import type { Tone } from "@/components/admin/kit";

export const Route = createFileRoute("/admin/")({ head: () => ({ meta: [{ title: "Dashboard — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: Dashboard });
const colors = ["oklch(0.55 0.22 264)", "oklch(0.68 0.17 155)", "oklch(0.78 0.16 70)", "oklch(0.65 0.12 300)", "oklch(0.62 0.13 215)", "oklch(0.75 0.02 255)"];
const statusTone = (status: string): Tone => status === "completed" ? "emerald" : status === "cancelled" ? "red" : status === "pending" ? "amber" : "blue";

function Dashboard() {
  const { data, isLoading, isError } = useQuery({ queryKey: ["admin-dashboard"], queryFn: api.admin.dashboard, refetchInterval: 60_000 });
  if (isLoading) return <div className="grid min-h-[60vh] place-items-center text-sm text-muted-foreground"><LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> Loading live operations…</div>;
  if (isError || !data) return <div className="p-8"><PageHeader title="Dashboard" description="Live operations overview" /><Panel><p className="font-semibold">The dashboard could not be loaded.</p><p className="mt-2 text-sm text-muted-foreground">Check the backend connection and admin session, then refresh.</p></Panel></div>;
  const dashboard = data as any;
  const cards = [
    [CalendarCheck, "blue", "Today's bookings", dashboard.bookingStats.today], [Clock3, "amber", "Pending jobs", dashboard.bookingStats.pending], [CheckCircle2, "emerald", "Completed jobs", dashboard.bookingStats.completed], [DollarSign, "indigo", "Monthly revenue", dashboard.revenue.monthly, "$"], [ShieldCheck, "violet", "Pending approvals", dashboard.pendingApprovalsCount], [Wrench, "cyan", "Technicians", dashboard.totalTechnicians], [UserPlus, "emerald", "Customers", dashboard.totalCustomers], [Star, "amber", "Average rating", dashboard.latestReviews.length ? (dashboard.latestReviews.reduce((total: number, review: any) => total + review.rating, 0) / dashboard.latestReviews.length).toFixed(1) : "—"],
  ] as const;
  return <>
    <PageHeader title="Dashboard" description="Live operational overview across ServicePro." actions={<><Button asChild variant="outline" size="sm"><Link to="/admin/verification"><ShieldCheck className="mr-1 h-4 w-4" /> Verification queue</Link></Button><Button asChild size="sm"><Link to="/admin/bookings">Manage bookings</Link></Button></>} />
    <div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{cards.map(([Icon, tone, label, value, prefix]) => <div key={label} className="rounded-2xl border border-border bg-card p-4 shadow-sm"><div className="flex items-start justify-between"><GlossyIcon icon={Icon} tone={tone as Tone} /><p className="text-2xl font-semibold tabular-nums">{prefix}{typeof value === "number" ? num(value) : value}</p></div><p className="mt-3 text-xs font-medium text-muted-foreground">{label}</p></div>)}</div>
    <div className="mt-6 grid gap-4 xl:grid-cols-3"><Panel className="xl:col-span-2" title="Revenue & bookings" description="Paid revenue and booking volume from the last seven days."><ResponsiveContainer width="100%" height={260}><AreaChart data={dashboard.weeklySeries}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors[0]} stopOpacity={0.35} /><stop offset="100%" stopColor={colors[0]} stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" /><YAxis /><Tooltip formatter={(value: number, name: string) => [name === "revenue" ? money(value) : value, name]} /><Area dataKey="revenue" stroke={colors[0]} fill="url(#revenue)" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></Panel><Panel title="Completed service mix"><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={dashboard.serviceDistribution} dataKey="value" nameKey="name" innerRadius={52} outerRadius={80}>{dashboard.serviceDistribution.map((_: any, index: number) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><ul className="space-y-1.5">{dashboard.serviceDistribution.map((service: any, index: number) => <li key={service.name} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full" style={{ background: colors[index % colors.length] }} /><span className="flex-1 text-muted-foreground">{service.name}</span><b>{num(service.value)}</b></li>)}</ul></Panel></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><Panel title="Bookings this week" className="xl:col-span-2"><ResponsiveContainer width="100%" height={220}><BarChart data={dashboard.weeklySeries}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" /><YAxis /><Tooltip /><Bar dataKey="bookings" fill={colors[0]} radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></Panel><Panel title="Top technicians" actions={<Link to="/admin/technicians" className="text-xs font-semibold text-primary">View all</Link>}><ul className="space-y-3">{dashboard.topTechnicians.map((technician: any) => <li key={technician._id} className="flex items-center gap-3"><Avatar className="h-9 w-9"><AvatarImage src={technician.user?.avatarUrl} /><AvatarFallback>{technician.user?.name?.[0]}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{technician.user?.name}</p><p className="text-xs text-muted-foreground">{technician.services?.[0]} · {num(technician.jobsCompleted)} jobs</p></div><span className="text-xs font-semibold">★ {technician.rating.toFixed(1)}</span></li>)}</ul></Panel></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><BookingList title="Recent bookings" items={dashboard.recentBookings} /><BookingList title="Upcoming jobs" items={dashboard.upcomingJobs} upcoming /><Panel title="Latest reviews" actions={<Link to="/admin/reviews" className="text-xs font-semibold text-primary">View all</Link>}><ul className="space-y-3">{dashboard.latestReviews.map((review: any) => <li key={review._id} className="rounded-xl border border-border p-3"><div className="flex items-center gap-2"><Avatar className="h-7 w-7"><AvatarImage src={review.customer?.avatarUrl} /><AvatarFallback>{review.customer?.name?.[0]}</AvatarFallback></Avatar><p className="text-sm font-medium">{review.customer?.name}</p><span className="ml-auto text-xs font-semibold">★ {review.rating}</span></div><p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{review.comment || "No written feedback."}</p></li>)}</ul></Panel></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><PeopleList title="Latest customers" items={dashboard.latestCustomers} link="/admin/customers" detail={(user: any) => user.city || "—"} /><PeopleList title="Latest technician applications" items={dashboard.latestTechnicians} link="/admin/verification" detail={(technician: any) => `${technician.services?.join(", ") || "No services"} · ${technician.verificationStatus}`} technician /></div>
  </>;
}
function BookingList({ title, items, upcoming = false }: { title: string; items: any[]; upcoming?: boolean }) { return <Panel title={title} actions={<Link to="/admin/bookings" className="text-xs font-semibold text-primary">View all</Link>}><ul className="space-y-3">{items.map((booking) => <li key={booking._id} className="flex items-center gap-3"><Avatar className="h-8 w-8"><AvatarImage src={booking.customer?.avatarUrl} /><AvatarFallback>{booking.customer?.name?.[0]}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{booking.service?.name}</p><p className="text-xs text-muted-foreground">{booking.customer?.name} · {upcoming ? new Date(booking.scheduledFor).toLocaleString() : booking.reference}</p></div><StatusPill label={booking.status.replace("_", " ")} tone={statusTone(booking.status)} /></li>)}</ul></Panel>; }
function PeopleList({ title, items, link, detail, technician = false }: { title: string; items: any[]; link: "/admin/customers" | "/admin/verification"; detail: (item: any) => string; technician?: boolean }) { return <Panel title={title} actions={<Link to={link} className="text-xs font-semibold text-primary">View all</Link>}><ul className="space-y-3">{items.map((item) => { const user = technician ? item.user : item; return <li key={item._id} className="flex items-center gap-3"><Avatar className="h-8 w-8"><AvatarImage src={user?.avatarUrl} /><AvatarFallback>{user?.name?.[0]}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{user?.name}</p><p className="truncate text-xs text-muted-foreground">{detail(item)}</p></div></li>; })}</ul></Panel>; }
