import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, CalendarDays, LoaderCircle, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EmptyState, PageHeader, Panel, StatusPill } from "@/components/admin/kit";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/admin/calendar")({ head: () => ({ meta: [{ title: "Calendar — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: CalendarPage });
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const statusMeta: Record<string, { label: string; tone: "amber" | "blue" | "emerald" | "red" | "slate" }> = { pending: { label: "Pending", tone: "amber" }, assigned: { label: "Assigned", tone: "blue" }, accepted: { label: "Accepted", tone: "blue" }, travelling: { label: "Travelling", tone: "blue" }, in_progress: { label: "In progress", tone: "blue" }, completed: { label: "Completed", tone: "emerald" }, cancelled: { label: "Cancelled", tone: "slate" }, disputed: { label: "Disputed", tone: "red" } };
type CalendarEvent = { bookingId: string; reference: string; date: string; title: string; status: string };

function CalendarPage() {
  const [view, setView] = useState<"month" | "week" | "day">("month"); const [cursor, setCursor] = useState(() => new Date());
  const year = cursor.getFullYear(); const month = cursor.getMonth() + 1;
  const calendar = useQuery({ queryKey: ["admin-calendar", year, month], queryFn: () => api.admin.calendar(`?year=${year}&month=${month}`) as Promise<{ year: number; month: number; events: CalendarEvent[] }> });
  const technicians = useQuery({ queryKey: ["admin-calendar-technicians"], queryFn: () => api.technicians.adminList("?status=approved&limit=100") });
  const events = calendar.data?.events ?? []; const title = new Intl.DateTimeFormat(undefined, { month: "long", year: "numeric" }).format(cursor);
  const monthDays = useMemo(() => { const first = new Date(year, month - 1, 1); const offset = (first.getDay() + 6) % 7; const count = new Date(year, month, 0).getDate(); return Array.from({ length: Math.ceil((offset + count) / 7) * 7 }, (_, index) => index - offset + 1); }, [year, month]);
  const shift = (amount: number) => setCursor((current) => new Date(current.getFullYear(), current.getMonth() + amount, 1));
  const eventsFor = (day: number) => events.filter((event) => new Date(event.date).getDate() === day);
  return <><PageHeader title="Calendar" description={`Live booking schedule for ${title}.`} crumbs={[{ label: "Calendar" }]} actions={<Tabs value={view} onValueChange={(value) => setView(value as typeof view)}><TabsList><TabsTrigger value="month">Month</TabsTrigger><TabsTrigger value="week">Week</TabsTrigger><TabsTrigger value="day">Day</TabsTrigger></TabsList></Tabs>} />
    <div className="grid gap-4 xl:grid-cols-4"><Panel className="xl:col-span-3" title={title} bodyClassName="p-3" actions={<span className="flex gap-1"><Button size="icon" variant="outline" className="h-8 w-8" onClick={() => shift(-1)}><ChevronLeft className="h-4 w-4" /></Button><Button size="icon" variant="outline" className="h-8 w-8" onClick={() => shift(1)}><ChevronRight className="h-4 w-4" /></Button></span>}>
      {calendar.isLoading ? <Loading /> : calendar.isError ? <EmptyState icon={CalendarDays} title="Could not load this calendar" description="Check the backend connection and administrator session." /> : view === "month" ? <div className="grid grid-cols-7 gap-1">{days.map((day) => <div key={day} className="pb-2 text-center text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{day}</div>)}{monthDays.map((day, index) => { const dayEvents = day > 0 && day <= new Date(year, month, 0).getDate() ? eventsFor(day) : []; return <div key={index} className={cn("min-h-[92px] rounded-xl border border-border p-1.5", day < 1 || day > new Date(year, month, 0).getDate() ? "bg-muted/30 opacity-50" : "bg-card")}><span className="text-[11px] font-semibold tabular-nums text-muted-foreground">{day > 0 && day <= new Date(year, month, 0).getDate() ? day : ""}</span><div className="mt-1 space-y-1">{dayEvents.slice(0, 2).map((event) => <Link key={event.bookingId} to="/admin/bookings/$bookingId" params={{ bookingId: event.bookingId }} className="block truncate rounded-md bg-primary/10 px-1.5 py-1 text-[10px] font-medium text-primary hover:bg-primary/15">{new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(event.date))} {event.title}</Link>)}{dayEvents.length > 2 && <p className="px-1 text-[10px] text-muted-foreground">+{dayEvents.length - 2} more</p>}</div></div>; })}</div> : <ScheduleList events={events} />}</Panel>
      <div className="space-y-4"><Panel title="Technician availability">{technicians.isLoading ? <Loading compact /> : technicians.isError ? <p className="text-sm text-muted-foreground">Could not load technicians.</p> : <ul className="space-y-2 text-sm">{(technicians.data ?? []).slice(0, 8).map((technician) => <li key={technician._id} className="flex items-center justify-between"><span className="truncate">{technician.user?.name || "Unnamed technician"}</span><StatusPill label={technician.isAvailable ? "Available" : "Unavailable"} tone={technician.isAvailable ? "emerald" : "amber"} /></li>)}{!(technicians.data ?? []).length && <li className="text-muted-foreground">No approved technicians yet.</li>}</ul>}</Panel><Panel title="Schedule notes"><p className="text-sm text-muted-foreground">Leave requests and holidays need a dedicated scheduling workflow. This calendar currently shows the live booking schedule only.</p></Panel></div></div>
  </>;
}
function ScheduleList({ events }: { events: CalendarEvent[] }) { return !events.length ? <EmptyState icon={CalendarDays} title="No scheduled bookings" description="There are no bookings in this month." /> : <ol className="divide-y divide-border">{events.map((event) => <li key={event.bookingId} className="flex gap-4 py-3"><span className="w-20 shrink-0 text-xs tabular-nums text-muted-foreground">{new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(event.date))}</span><Link to="/admin/bookings/$bookingId" params={{ bookingId: event.bookingId }} className="flex-1 rounded-xl border border-primary/20 bg-primary/5 px-3 py-2 hover:bg-primary/10"><p className="text-sm font-medium">{event.title}</p><StatusPill className="mt-1" {...(statusMeta[event.status] ?? { label: event.status, tone: "slate" })} /></Link></li>)}</ol>; }
function Loading({ compact = false }: { compact?: boolean }) { return <div className={cn("flex justify-center text-muted-foreground", compact ? "py-4 text-sm" : "py-16")}><LoaderCircle className="mr-2 h-5 w-5 animate-spin" />Loading…</div>; }
