import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { ResponsiveContainer, AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RTooltip, Legend } from "recharts";
import { FileSpreadsheet, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EmptyState, PageHeader, Panel } from "@/components/admin/kit";
import { api, API_BASE_URL, tokenStore, type ApiReport } from "@/lib/api";

export const Route = createFileRoute("/admin/reports")({ head: () => ({ meta: [{ title: "Reports — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: ReportsPage });
const money = (value: number) => new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

function ReportsPage() {
  const [range, setRange] = useState<ApiReport["range"]>("30d"); const [downloading, setDownloading] = useState(false);
  const report = useQuery({ queryKey: ["admin-report", range], queryFn: () => api.admin.report(range) });
  const download = async () => { setDownloading(true); try { const response = await fetch(`${API_BASE_URL}/admin/reports/export?range=${range}`, { headers: { Authorization: `Bearer ${tokenStore.get()}` }, credentials: "include" }); if (!response.ok) throw new Error("Could not generate CSV report"); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = `servicepro-report-${range}.csv`; link.click(); URL.revokeObjectURL(url); } finally { setDownloading(false); } };
  const data = report.data;
  return <><PageHeader title="Reports" description="Backend-generated operational and financial reporting." crumbs={[{ label: "Reports" }]} actions={<><Tabs value={range} onValueChange={(value) => setRange(value as ApiReport["range"])}><TabsList><TabsTrigger value="7d">7 days</TabsTrigger><TabsTrigger value="30d">30 days</TabsTrigger><TabsTrigger value="12m">12 months</TabsTrigger></TabsList></Tabs><Button size="sm" className="gap-1.5" disabled={downloading || report.isLoading} onClick={download}>{downloading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <FileSpreadsheet className="h-4 w-4" />}Download CSV</Button></>} />{report.isLoading ? <Loading /> : report.isError || !data ? <EmptyState icon={FileSpreadsheet} title="Could not generate report" description="Check the backend connection and administrator session." /> : <ReportContent report={data} />}</>;
}
function ReportContent({ report }: { report: ApiReport }) { const cards = [["Revenue", money(report.metrics.revenue)], ["Bookings", report.metrics.bookings.toLocaleString()], ["New customers", report.metrics.customers.toLocaleString()], ["Cancellation rate", `${report.metrics.cancellationRate}%`], ["Average rating", report.metrics.averageRating.toFixed(2)], ["Approved technicians", report.metrics.approvedTechnicians.toLocaleString()]]; return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value]) => <Panel key={label}><p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(report.from).toLocaleDateString()} – {new Date(report.to).toLocaleDateString()}</p></Panel>)}</div><div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_1fr]"><Panel title="Paid revenue"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={report.revenueSeries}><defs><linearGradient id="rep-rev" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="oklch(0.55 0.22 264)" stopOpacity={0.35} /><stop offset="100%" stopColor="oklch(0.55 0.22 264)" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 12 }} /><YAxis tick={{ fontSize: 12 }} /><RTooltip formatter={(value: number) => money(value)} /><Legend /><Area type="monotone" dataKey="revenue" stroke="oklch(0.55 0.22 264)" fill="url(#rep-rev)" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></div></Panel><Panel title="Bookings by service"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.serviceDistribution} layout="vertical" margin={{ left: 24 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" /><YAxis type="category" dataKey="name" width={110} tick={{ fontSize: 12 }} /><RTooltip /><Bar dataKey="value" fill="oklch(0.55 0.22 264)" radius={[0, 8, 8, 0]} /></BarChart></ResponsiveContainer></div></Panel></div></>; }
function Loading() { return <div className="flex justify-center py-20 text-muted-foreground"><LoaderCircle className="mr-2 h-5 w-5 animate-spin" />Generating report…</div>; }
