import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { ShieldCheck, Search, Clock3, FileCheck2, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EmptyState, GlossyIcon, PageHeader, Panel, StatusPill } from "@/components/admin/kit";
import { api, type ApiTechnician } from "@/lib/api";

export const Route = createFileRoute("/admin/verification/")({ head: () => ({ meta: [{ title: "Verification Queue — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: VerificationQueue });
const meta = { pending: { label: "Pending", tone: "amber" as const }, under_review: { label: "Under review", tone: "blue" as const }, rejected: { label: "Rejected", tone: "red" as const }, suspended: { label: "Suspended", tone: "slate" as const }, approved: { label: "Approved", tone: "emerald" as const } };
const name = (t: ApiTechnician) => t.user?.name || "Unnamed technician";
const date = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—";

function VerificationQueue() {
  const [tab, setTab] = useState("pending"); const [q, setQ] = useState("");
  const { data: technicians = [], isLoading, isError, refetch } = useQuery({ queryKey: ["admin-verification"], queryFn: () => api.technicians.adminList("?limit=100") });
  const counts = { pending: technicians.filter((t) => t.verificationStatus === "pending").length, under_review: technicians.filter((t) => t.verificationStatus === "under_review").length, rejected: technicians.filter((t) => t.verificationStatus === "rejected").length, approved: technicians.filter((t) => t.verificationStatus === "approved").length };
  const list = technicians.filter((t) => (tab === "all" ? t.verificationStatus !== "approved" : t.verificationStatus === tab) && [name(t), t.user?.email, t.city, t.services.join(" ")].join(" ").toLowerCase().includes(q.toLowerCase()));
  return <><PageHeader title="Technician Verification" description="No technician receives bookings until an owner approves their application." crumbs={[{ label: "Verification Queue" }]} />
    <div className="mb-5 grid gap-4 sm:grid-cols-3"><Metric icon={ShieldCheck} tone="blue" value={counts.pending} label="Awaiting first review" /><Metric icon={Clock3} tone="amber" value={counts.under_review} label="Under review" /><Metric icon={FileCheck2} tone="emerald" value={counts.approved} label="Approved to date" /></div>
    <Panel bodyClassName="p-0"><div className="flex flex-wrap items-center gap-3 border-b border-border p-4"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="pending">Pending ({counts.pending})</TabsTrigger><TabsTrigger value="under_review">Under review ({counts.under_review})</TabsTrigger><TabsTrigger value="rejected">Rejected ({counts.rejected})</TabsTrigger><TabsTrigger value="all">All open</TabsTrigger></TabsList></Tabs><div className="relative ml-auto min-w-[200px] flex-1 sm:max-w-xs"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search applicants" className="h-9 pl-9" /></div></div>
      {isLoading ? <div className="flex justify-center py-16 text-muted-foreground"><LoaderCircle className="mr-2 h-5 w-5 animate-spin" />Loading applications…</div> : isError ? <EmptyState icon={ShieldCheck} title="Could not load applications" description="Check the backend connection and your administrator session." action={<Button size="sm" onClick={() => refetch()}>Try again</Button>} /> : list.length === 0 ? <EmptyState icon={ShieldCheck} title="Queue is clear" description="No applications are waiting in this state. New technician sign-ups will land here automatically." action={<Button asChild size="sm"><Link to="/admin/technicians">View technician roster</Link></Button>} /> : <div className="grid gap-4 p-4 md:grid-cols-2 xl:grid-cols-3">{list.map((t) => <article key={t._id} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start gap-3"><Avatar className="h-12 w-12 ring-2 ring-primary/15"><AvatarImage src={t.user?.avatarUrl} alt={name(t)} /><AvatarFallback>{name(t)[0]}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{name(t)}</p><p className="text-xs text-muted-foreground">{t.experienceYears} yrs experience · {t.city}</p></div><StatusPill {...meta[t.verificationStatus ?? "pending"]} /></div><p className="mt-3 text-xs text-muted-foreground">Applied for</p><div className="mt-1 flex flex-wrap gap-1.5">{t.services.map((service) => <span key={service} className="rounded-lg bg-muted px-2 py-0.5 text-[11px] font-medium">{service}</span>)}</div>{t.reviewNotes && <p className="mt-3 rounded-xl bg-destructive/8 p-2.5 text-[11px] text-destructive"><span className="font-semibold">Review note:</span> {t.reviewNotes}</p>}<div className="mt-4 flex items-center justify-between"><span className="text-[11px] tabular-nums text-muted-foreground">Applied {date(t.createdAt)}</span><Button asChild size="sm" className="btn-press"><Link to="/admin/verification/$techId" params={{ techId: t._id }}>Review application</Link></Button></div></article>)}</div>}</Panel>
  </>;
}
function Metric({ icon, tone, value, label }: { icon: React.ComponentType<{ className?: string; strokeWidth?: number }>; tone: "blue" | "amber" | "emerald"; value: number; label: string }) { return <div className="flex items-center gap-4 rounded-2xl border border-border bg-card p-5"><GlossyIcon icon={icon} tone={tone} size="lg" /><div><p className="text-3xl font-semibold tabular-nums tracking-tight">{value}</p><p className="text-xs font-medium text-muted-foreground">{label}</p></div></div>; }
