import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Bell, Check, CalendarCheck, ShieldCheck, CreditCard, LifeBuoy, ServerCog, LoaderCircle, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EmptyState, GlossyIcon, PageHeader, Panel, StatusPill } from "@/components/admin/kit";
import { api, type ApiAdminNotification } from "@/lib/api";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/notifications")({ head: () => ({ meta: [{ title: "Notifications — ServicePro Admin" }, { name: "robots", content: "noindex" }] }), component: NotificationsPage });
const meta: Record<ApiAdminNotification["category"], { tone: "blue" | "violet" | "amber" | "emerald" | "slate"; icon: React.ComponentType<{ className?: string; strokeWidth?: number }>; label: string }> = { booking: { tone: "blue", icon: CalendarCheck, label: "Bookings" }, contact: { tone: "amber", icon: LifeBuoy, label: "Website contact" }, technician: { tone: "violet", icon: ShieldCheck, label: "Technicians" }, payment: { tone: "emerald", icon: CreditCard, label: "Payments" }, system: { tone: "slate", icon: ServerCog, label: "System" } };
const time = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

function NotificationsPage() {
  const client = useQueryClient(); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const notices = useQuery({ queryKey: ["admin-notifications"], queryFn: () => api.notifications.list("?limit=100") });
  const invalidate = () => client.invalidateQueries({ queryKey: ["admin-notifications"] });
  const markOne = useMutation({ mutationFn: (id: string) => api.notifications.markRead(id, true), onSuccess: invalidate, onError: (error) => toast.error(error instanceof Error ? error.message : "Could not update notification") });
  const markAll = useMutation({ mutationFn: api.notifications.markAllRead, onSuccess: () => { invalidate(); toast.success("All notifications marked read"); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Could not update notifications") });
  const sendToTechnicians = useMutation({ mutationFn: () => api.notifications.sendToTechnicians(title.trim(), body.trim()), onSuccess: ({ delivered }) => { setTitle(""); setBody(""); toast.success(`Notification sent to ${delivered} technician${delivered === 1 ? "" : "s"}`); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Could not send notification") });
  const items = notices.data ?? []; const unread = items.filter((item) => !item.read);
  return <><PageHeader title="Notifications" description="Live operational alerts for website contacts, bookings, technician activity, payments, and system events." crumbs={[{ label: "Notifications" }]} actions={<Button size="sm" variant="outline" disabled={!unread.length || markAll.isPending} onClick={() => markAll.mutate()}>{markAll.isPending ? <LoaderCircle className="mr-1.5 h-4 w-4 animate-spin" /> : <Check className="mr-1.5 h-4 w-4" />}Mark all read</Button>} /><div className="grid gap-4 lg:grid-cols-[1fr_300px]"><Panel bodyClassName="p-0"><Tabs defaultValue="unread" className="p-4"><TabsList><TabsTrigger value="unread">Unread ({unread.length})</TabsTrigger><TabsTrigger value="all">All ({items.length})</TabsTrigger></TabsList>{(["unread", "all"] as const).map((tab) => <TabsContent key={tab} value={tab} className="mt-4 space-y-2"><NotificationList items={tab === "unread" ? unread : items} loading={notices.isLoading} error={notices.isError} onRead={(id) => markOne.mutate(id)} pending={markOne.isPending} /></TabsContent>)}</Tabs></Panel><div className="space-y-4"><Panel title="Notify technicians" description="Sends to every approved technician and their live session."><div className="space-y-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Notification title" maxLength={180} /><Textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Message for technicians…" rows={4} maxLength={1000} /><Button className="w-full gap-1.5" disabled={!title.trim() || !body.trim() || sendToTechnicians.isPending} onClick={() => sendToTechnicians.mutate()}>{sendToTechnicians.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}Send to approved technicians</Button></div></Panel><Panel title="Alert rules"><ul className="space-y-3 text-sm text-muted-foreground"><li>Website Contact Form submissions, with repeat contacts elevated to urgent.</li><li>New and emergency bookings created by customers.</li><li>Technician applications and verification decisions.</li><li>Payment events can be added as soon as the payment provider webhook is enabled.</li></ul></Panel><Panel title="Delivery"><StatusPill label="Live admin feed" tone="emerald" /><p className="mt-3 text-xs text-muted-foreground">New events are stored in the backend and also emitted to connected admin sessions.</p></Panel></div></div></>;
}
function NotificationList({ items, loading, error, onRead, pending }: { items: ApiAdminNotification[]; loading: boolean; error: boolean; onRead: (id: string) => void; pending: boolean }) { if (loading) return <div className="flex justify-center py-16 text-muted-foreground"><LoaderCircle className="mr-2 h-5 w-5 animate-spin" />Loading notifications…</div>; if (error) return <EmptyState icon={Bell} title="Could not load notifications" description="Check the backend connection and administrator session." />; if (!items.length) return <EmptyState icon={Bell} title="You're all caught up" description="New operational events will appear here." />; return <div className="space-y-2">{items.map((item) => { const itemMeta = meta[item.category]; const content = <><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.body}</p></>; return <div key={item._id} className="flex gap-3 rounded-xl border border-border p-3.5"><GlossyIcon icon={itemMeta.icon} tone={itemMeta.tone} size="sm" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2">{item.link ? <Link to={item.link as any} className="hover:underline">{content}</Link> : content}<span className="shrink-0 text-[11px] text-muted-foreground">{time(item.createdAt)}</span></div><div className="mt-2 flex items-center justify-between"><StatusPill label={itemMeta.label} tone={itemMeta.tone} />{!item.read && <button disabled={pending} className="text-[11px] font-semibold text-primary hover:underline" onClick={() => onRead(item._id)}>Mark read</button>}</div></div></div>; })}</div>; }
