/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as BookRouteImport } from './routes/book'
import { Route as BecomeATechnicianRouteImport } from './routes/become-a-technician'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechniciansIndexRouteImport } from './routes/technicians.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TechniciansSlugRouteImport } from './routes/technicians.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminTechniciansRouteImport } from './routes/admin.technicians'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminVerificationIndexRouteImport } from './routes/admin.verification.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as AdminVerificationTechIdRouteImport } from './routes/admin.verification.$techId'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin.bookings.$bookingId'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATechnicianRoute = BecomeATechnicianRouteImport.update({
  id: '/become-a-technician',
  path: '/become-a-technician',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansIndexRoute = TechniciansIndexRouteImport.update({
  id: '/technicians/',
  path: '/technicians/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TechniciansSlugRoute = TechniciansSlugRouteImport.update({
  id: '/technicians/$slug',
  path: '/technicians/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationIndexRoute = AdminVerificationIndexRouteImport.update({
  id: '/verification/',
  path: '/verification/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationTechIdRoute = AdminVerificationTechIdRouteImport.update({
  id: '/verification/$techId',
  path: '/verification/$techId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/apply': typeof ApplyRoute
  '/become-a-technician': typeof BecomeATechnicianRoute
  '/book': typeof BookRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/why-us': typeof WhyUsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/technicians/$slug': typeof TechniciansSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/verification/$techId': typeof AdminVerificationTechIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/apply': typeof ApplyRoute
  '/become-a-technician': typeof BecomeATechnicianRoute
  '/book': typeof BookRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/why-us': typeof WhyUsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/technicians/$slug': typeof TechniciansSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/technicians': typeof TechniciansIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/verification/$techId': typeof AdminVerificationTechIdRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/verification': typeof AdminVerificationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/apply': typeof ApplyRoute
  '/become-a-technician': typeof BecomeATechnicianRoute
  '/book': typeof BookRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/why-us': typeof WhyUsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/technicians/$slug': typeof TechniciansSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/verification/$techId': typeof AdminVerificationTechIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/apply'
    | '/become-a-technician'
    | '/book'
    | '/booking-confirmation'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/sitemap.xml'
    | '/track'
    | '/why-us'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/support'
    | '/admin/technicians'
    | '/services/$slug'
    | '/technicians/$slug'
    | '/admin/'
    | '/services/'
    | '/technicians/'
    | '/admin/bookings/$bookingId'
    | '/admin/verification/$techId'
    | '/admin/bookings/'
    | '/admin/verification/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/apply'
    | '/become-a-technician'
    | '/book'
    | '/booking-confirmation'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/sitemap.xml'
    | '/track'
    | '/why-us'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/support'
    | '/admin/technicians'
    | '/services/$slug'
    | '/technicians/$slug'
    | '/admin'
    | '/services'
    | '/technicians'
    | '/admin/bookings/$bookingId'
    | '/admin/verification/$techId'
    | '/admin/bookings'
    | '/admin/verification'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/apply'
    | '/become-a-technician'
    | '/book'
    | '/booking-confirmation'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/sitemap.xml'
    | '/track'
    | '/why-us'
    | '/admin/calendar'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/support'
    | '/admin/technicians'
    | '/services/$slug'
    | '/technicians/$slug'
    | '/admin/'
    | '/services/'
    | '/technicians/'
    | '/admin/bookings/$bookingId'
    | '/admin/verification/$techId'
    | '/admin/bookings/'
    | '/admin/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApplyRoute: typeof ApplyRoute
  BecomeATechnicianRoute: typeof BecomeATechnicianRoute
  BookRoute: typeof BookRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  WhyUsRoute: typeof WhyUsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TechniciansSlugRoute: typeof TechniciansSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TechniciansIndexRoute: typeof TechniciansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-technician': {
      id: '/become-a-technician'
      path: '/become-a-technician'
      fullPath: '/become-a-technician'
      preLoaderRoute: typeof BecomeATechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians/': {
      id: '/technicians/'
      path: '/technicians'
      fullPath: '/technicians/'
      preLoaderRoute: typeof TechniciansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/technicians/$slug': {
      id: '/technicians/$slug'
      path: '/technicians/$slug'
      fullPath: '/technicians/$slug'
      preLoaderRoute: typeof TechniciansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification/': {
      id: '/admin/verification/'
      path: '/verification'
      fullPath: '/admin/verification/'
      preLoaderRoute: typeof AdminVerificationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification/$techId': {
      id: '/admin/verification/$techId'
      path: '/verification/$techId'
      fullPath: '/admin/verification/$techId'
      preLoaderRoute: typeof AdminVerificationTechIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTechniciansRoute: typeof AdminTechniciansRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
  AdminVerificationTechIdRoute: typeof AdminVerificationTechIdRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminVerificationIndexRoute: typeof AdminVerificationIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTechniciansRoute: AdminTechniciansRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
  AdminVerificationTechIdRoute: AdminVerificationTechIdRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminVerificationIndexRoute: AdminVerificationIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApplyRoute: ApplyRoute,
  BecomeATechnicianRoute: BecomeATechnicianRoute,
  BookRoute: BookRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  WhyUsRoute: WhyUsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TechniciansSlugRoute: TechniciansSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TechniciansIndexRoute: TechniciansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
